// Détecte les variables manuelles dans un template
export function detectManualVariables(htmlContent, existingCustomFields = []) {
  if (!htmlContent) return [];
  
  // Extraire toutes les variables {{variable}}
  const variableRegex = /\{\{(\w+)\}\}/g;
  const allVariables = new Set();
  let match;
  
  while ((match = variableRegex.exec(htmlContent)) !== null) {
    allVariables.add(match[1]);
  }
  
  // Variables auto-générées (employé, établissement, calculées)
  const autoGeneratedVariables = new Set([
    // Établissement
    'etablissementNom', 'etablissementSiret', 'etablissementEmail', 'etablissementSite',
    'etablissementAdresse', 'villeEtablissement', 'etablissementAdresseLivraison',
    'responsableNom', 'responsableTel', 'responsableEmail',
    
    // Employé
    'prenom', 'nom', 'naissance', 'lieuNaissance', 'adresse', 'nationalite', 'secu',
    'poste', 'taches', 'debut', 'fin', 'heures', 'heuresTexte', 'periodeEssaiTexte',
    'finEssai', 'taux', 'salaireBrut', 'motifCDD',
    
    // Calculées/système
    'signature', 'dateDebutContrat', 'fonctionOccupee'
  ]);
  
  // Variables manuelles = toutes - auto-générées
  const manualVariables = [];
  
  allVariables.forEach(variable => {
    if (!autoGeneratedVariables.has(variable)) {
      // Vérifier si déjà définie dans customFields
      const existingField = existingCustomFields.find(f => f.key === variable);
      
      if (existingField) {
        manualVariables.push(existingField);
      } else {
        // Détecter automatiquement le type
        manualVariables.push(inferVariableType(variable));
      }
    }
  });
  
  return manualVariables;
}

// Inférer le type d'une variable à partir de son nom
function inferVariableType(variableName) {
  const name = variableName.toLowerCase();
  
  // Détection date
  if (name.includes('date')) {
    return {
      key: variableName,
      label: formatLabel(variableName),
      type: 'date',
      required: true,
      placeholder: 'JJ/MM/AAAA'
    };
  }
  
  // Détection heure
  if (name.includes('heure') || name.includes('time')) {
    return {
      key: variableName,
      label: formatLabel(variableName),
      type: 'text',
      required: false,
      placeholder: '14:30'
    };
  }
  
  // Détection description/faits/motif = textarea
  if (name.includes('description') || name.includes('faits') || name.includes('motif')) {
    return {
      key: variableName,
      label: formatLabel(variableName),
      type: 'textarea',
      required: true,
      placeholder: 'Détaillez de manière factuelle, avec dates et lieux précis...',
      helpText: '⚠️ Restez factuel : dates, lieux, témoins, faits observables',
      maxLength: 2000
    };
  }
  
  // Détection montant/indemnité
  if (name.includes('montant') || name.includes('indemn') || name.includes('salaire')) {
    return {
      key: variableName,
      label: formatLabel(variableName),
      type: 'number',
      required: false,
      placeholder: '0.00'
    };
  }
  
  // Détection lieu
  if (name.includes('lieu')) {
    return {
      key: variableName,
      label: formatLabel(variableName),
      type: 'text',
      required: false,
      placeholder: 'Adresse ou lieu'
    };
  }
  
  // Par défaut : text
  return {
    key: variableName,
    label: formatLabel(variableName),
    type: 'text',
    required: false,
    placeholder: ''
  };
}

// Formater le label à partir du nom de variable
function formatLabel(variableName) {
  // Mapping des labels connus
  const knownLabels = {
    'dateFaits': 'Date des faits reprochés',
    'descriptionFaits': 'Description détaillée des faits reprochés',
    'dateNotification': 'Date de notification',
    'dateConvocation': 'Date de convocation',
    'lieuConvocation': 'Lieu de convocation',
    'heureConvocation': 'Heure de convocation',
    'dateIncident': 'Date de l\'incident',
    'motifModification': 'Motif de la modification',
    'ancienneValeur': 'Ancienne valeur',
    'nouvelleValeur': 'Nouvelle valeur',
    'dateEffet': 'Date d\'effet',
    'dateRupture': 'Date de rupture',
    'motifRupture': 'Motif de rupture',
    'dateFinContrat': 'Date de fin de contrat',
    'indemnitePreavis': 'Indemnité de préavis (€)',
    'indemniteRupture': 'Indemnité de rupture (€)',
    'periodeAttestation': 'Période concernée',
    'natureAttestation': 'Nature de l\'attestation'
  };
  
  if (knownLabels[variableName]) {
    return knownLabels[variableName];
  }
  
  // Conversion camelCase vers texte lisible
  return variableName
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, str => str.toUpperCase())
    .trim();
}